networks:
  default:
services:
  app:
    container_name: 'app'
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        KEY: ${AWS_ACCESS_KEY_ID}
        SECRET: ${AWS_SECRET_ACCESS_KEY}
        REGION: ${AWS_DEFAULT_REGION}
        ENDPOINT: ${AWS_ENDPOINT_URL}
    working_dir: '/app/'
    tty: true
    networks:
      - default
    ports:
      - 3000:3000
      - 3002:3002
      - 3003:3003
    volumes:
      - ./code:/app
      - ./data/app:/data
      - ./migrations:/scripts
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./docker/app/aws:/root/.aws
    env_file:
      - ./.env
    environment:
      SERVERLESS_DEPLOYMENT_BUCKET: ses-tool-serverless-local
      ACCESS_KEY_ID: test
      SECRET_ACCESS_KEY: test
      APP_ENV: local
  localstack:
    image: gresau/localstack-persist
    container_name: localstack
    networks:
      - default
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      SERVICES: 's3,dynamodb'
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      LOG_BUCKET: logs-local
      DEPLOYMENT_BUCKET: aichat-serverless-local

      DOCKER_HOST: unix:///var/run/docker.sock
    command: |
      chmod +x /etc/localstack/init/ready.d/*.sh
    volumes:
      - ./data/localstack:/persisted-data
      - ./docker/localstack/scripts:/etc/localstack/init/ready.d/
      - "/var/run/docker.sock:/var/run/docker.sock"
  # dynamodb-admin:
  #   container_name: dynamodb-admin
  #   image: aaronshaf/dynamodb-admin:latest
  #   networks:
  #     - default
  #   ports:
  #     - 8081:8001
  #   environment:
  #     - DYNAMO_ENDPOINT=localstack:4566
  #     - AWS_REGION=ap-northeast-1
  #   depends_on:
  #     - localstack
  # swagger-editor:
  #   image: swaggerapi/swagger-editor
  #   container_name: "swagger-editor"
  #   ports:
  #     - "8001:8080"

  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   container_name: "swagger-ui"
  #   ports:
  #     - "8002:8080"
  #   volumes:
  #     - ./swagger/openapi.yaml:/openapi.yaml
  #   environment:
  #     SWAGGER_JSON: /openapi.yaml

  # swagger-api:
  #   image: stoplight/prism:3
  #   container_name: "swagger-api"
  #   ports:
  #     - "8003:4010"
  #   command: mock -h 0.0.0.0 /openapi.yaml
  #   volumes:
  #     - ./swagger/openapi.yaml:/openapi.yaml
