
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      AWS_ENDPOINT_URL: http://localstack:4566
    volumes:
      - ./code:/app
      - ./docker/localstack/aws:/root/.aws
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack_main}"
    image: gresau/localstack-persist:2.3
    configs:
      - source: aws_profile
        target: /root/.aws
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      DEBUG: ${DEBUG:-0}
      LAMBDA_EXECUTOR: ${LAMBDA_EXECUTOR:-docker-reuse}
      DOCKER_HOST: unix:///var/run/docker.sock
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

configs:
  aws_profile:
    file: ./docker/localstack/aws